Default: &defaults
  user: backoffice
  password: backoffice
  host: localhost
  port: 3306
  database: backoffice
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: backoffice_test
  <<: *defaults

Staging:
  database: backoffice_staging
  poolsize: 100
  <<: *defaults

Production:
  database: backoffice_production
  poolsize: 100
  <<: *defaults
